### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by smartins** [MyCryptoHQ/MyCrypto#1920]
I'm following the steps at the following page to use Ledger Nano S with my local node:
https://support.mycrypto.com/offline/using-ledger-wallet-offline.html

npm: 6.1.0
node: 8.11.2

Did `npm install` on Windows 10 x64 but I get the following error:

```
H:\Parity\MyCrypto-1.0.2>npm install

> scrypt@6.0.3 preinstall H:\Parity\MyCrypto-1.0.2\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install H:\Parity\MyCrypto-1.0.2\node_modules\scrypt
> node-gyp rebuild


H:\Parity\MyCrypto-1.0.2\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\Steven Martins\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Steven Martins\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "Y:\Work\Web\Tools\Development\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Steven Martins\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Steven Martins\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Steven Martins\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17682
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Steven Martins\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\Parity\MyCrypto-1.0.2\node_modules\scrypt
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@22.4.3 requires a peer of jest@^22.4.0 || ^22.5.0-alpha.1 || ^23.0.0-alpha.1 but none is installed. You must install peer dependencies yourself.
npm WARN MyCrypto@1.0.2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.8.3 (node_modules\app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.8.3: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.3 (node_modules\app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-linux@1.7.2 (node_modules\dmg-builder\node_modules\app-builder-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-linux@1.7.2: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.7.2 (node_modules\dmg-builder\node_modules\app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.7.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Steven Martins\AppData\Roaming\npm-cache\_logs\2018-06-08T15_50_48_018Z-debug.log
```

**Comment by dternyak** [comment]
> gyp ERR! stack Error: Can't find Python executable "Y:\Work\Web\Tools\Development\Python\Python36-32\python.EXE", you can set the PYTHON env variable.

Looks like you have an issue with Python on your system. Let me know if you need help, but simply installing Python and re-trying will hopefully fix things for you! I don't know much about Windows unfortunately, so that's the best advice I have.

**Comment by smartins** [comment]
Thanks for the pointers, here are the steps I had to use to be able to install:

Run: `npm install --global --production windows-build-tools`
(Installs python 2.7, visual studio, .net framework and other required windows tools)

Run:  `npm config set msvs_version 2015`
Run: `npm install`

`npm run dev` executes but when browsing to http://localhost:3000/ I get the following error:

```
ERROR in ./common/components/WalletDecrypt/components/ViewOnly.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--6-2!./common/components/WalletDecrypt/components/ViewOnly.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir 'H:\Parity\MyCrypto-1.0.2\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (H:\Parity\MyCrypto-1.0.2\node_modules\node-sass\lib\extensions.js:129:13)
    at foundBinariesList (H:\Parity\MyCrypto-1.0.2\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (H:\Parity\MyCrypto-1.0.2\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (H:\Parity\MyCrypto-1.0.2\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (H:\Parity\MyCrypto-1.0.2\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (H:\Parity\MyCrypto-1.0.2\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (H:\Parity\MyCrypto-1.0.2\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./common/components/WalletDecrypt/components/ViewOnly.scss 2:14-148 21:1-42:3 21:146-42:2 22:19-153
 @ ./common/components/WalletDecrypt/components/ViewOnly.tsx
 @ ./common/components/WalletDecrypt/components/index.tsx
 @ ./common/components/WalletDecrypt/WalletDecrypt.tsx
 @ ./common/components/WalletDecrypt/index.tsx
 @ ./common/components/index.ts
 @ ./common/containers/QrSignerModal/index.tsx
 @ ./common/Root.tsx
 @ ./common/index.tsx
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true webpack/hot/only-dev-server ./common/index.tsx
```

My guess is that a required dependency was not installed.

**Comment by smartins** [comment]
Now down to hopefully the last issue.

`npm run dev` works and loads MyCrypto at http://localhost:3000
`npm run dev:https` gives the error:
```
'HTTPS' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyCrypto@1.0.2 dev:https: `HTTPS=true node webpack_config/devServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MyCrypto@1.0.2 dev:https script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I then tried `npm run dev --https` which complies just fine but does not bind the https:// only http://
Exactly the same for `npm run dev "HTTPS=true node webpack_config/devServer.js"`, only http:// binded

Any idea how I can get https:// working? The main reason to run this locally was to be able to use my Ledger with my local parity node.

**Comment by smartins** [comment]
Found a way to "fix" it. I changed the following line on devServer.js:

FROM:
`"dev:https": "HTTPS=true node webpack_config/devServer.js",`

TO:
`"dev:https": "set HTTPS=true&& node webpack_config/devServer.js",`

**Comment by wbobeirne** [comment]
I believe these are operating specific changes, we should use a module like https://www.npmjs.com/package/cross-env to make sure this behaves the same on all environments.
